### ISSUE TITLE
screen cap for readme

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/align-text#2]
![screen shot 2015-06-09 at 2 08 34 am](https://cloud.githubusercontent.com/assets/383994/8051597/7b716fbc-0e4c-11e5-9aef-4493fd22db58.png)

**Comment by shinnn** [comment]
Seems fixed in https://github.com/jonschlinkert/align-text/commit/b3f7b18af143242c5cc03eec7496c02d92b49b09.

**Comment by jonschlinkert** [comment]
this is just an image for the readme. if you paste an image into the comment box, it [creates a link](https://github.com/jonschlinkert/align-text/commit/b3f7b18af143242c5cc03eec7496c02d92b49b09#diff-8191924d78e7652d71643c49ac2716c8R16) that you can drop into a markdown doc. 

thanks for the reminder!

**Comment by shinnn** [comment]
Ah, OK. I understood what you did :)
